<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>gunicorn spawn worker exception</title>
<meta name="generator" content="Org mode" />
<meta name="author" content="dirtysalt" />
<link rel="shortcut icon" href="/themes/favicon.ico" /><link rel="stylesheet" type="text/css" href="/themes/simple.css"/></head>
<body>
<div id="content">
<h1 class="title">gunicorn spawn worker exception</h1>
<div id="table-of-contents">
<h2>Table of Contents</h2>
<div id="text-table-of-contents">
<ul>
<li><a href="#orgf18de76">1. 事故现场</a></li>
<li><a href="#org8fa9d90">2. 事故分析</a></li>
</ul>
</div>
</div>

<div id="outline-container-orgf18de76" class="outline-2">
<h2 id="orgf18de76"><span class="section-number-2">1</span> 事故现场</h2>
<div class="outline-text-2" id="text-1">
<p>
@2019-08-13T10:40:41
</p>

<p>
上周gunicorn事故，在其他webapp也出现了类似状况(push_rpc_server)。当时是data_rpc_server出现故障，但是日志里面没有具体原因
</p>

<div class="org-src-container">
<pre class="src src-python">Traceback (most recent call last):
  File <span class="org-string">"src/gevent/greenlet.py"</span>, line <span class="org-py-number">716</span>, <span class="org-keyword">in</span> gevent._greenlet.Greenlet.run
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/arbiter.py"</span>, line <span class="org-py-number">245</span>, <span class="org-keyword">in</span> handle_chld
    <span class="org-py-object-reference">self</span>.reap_workers()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/arbiter.py"</span>, line <span class="org-py-number">525</span>, <span class="org-keyword">in</span> reap_workers
    <span class="org-keyword">raise</span> HaltServer(reason, <span class="org-py-object-reference">self</span>.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: &lt;HaltServer <span class="org-string">'Worker failed to boot.'</span> <span class="org-py-number">3</span>&gt;
<span class="org-py-number">2019</span>-<span class="org-py-number">08</span>-06T05:<span class="org-py-number">53</span>:55Z &lt;Greenlet <span class="org-string">"Greenlet-0"</span> at 0x7efd3483ca48: &lt;bound method Arbiter.handle_chld of &lt;gunicorn.arbiter.Arbiter <span class="org-py-builtins">object</span> at 0x7efd34746978&gt;&gt;(<span class="org-py-number">17</span>, <span class="org-py-pseudo-keyword">None</span>)&gt; failed <span class="org-keyword">with</span> HaltServer
</pre>
</div>

<p>
然后今天 push_rpc_server 也出现类似故障，但是保存了错误日志
</p>

<div class="org-src-container">
<pre class="src src-python">[<span class="org-py-number">2019</span>-<span class="org-py-number">08</span>-<span class="org-py-number">12</span> <span class="org-py-number">07</span>:<span class="org-py-number">09</span>:<span class="org-py-number">52</span> +<span class="org-py-number">0000</span>] [<span class="org-py-number">45142</span>] [ERROR] <span class="org-py-exception-name">Exception</span> <span class="org-keyword">in</span> worker process
Traceback (most recent call last):
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/arbiter.py"</span>, line <span class="org-py-number">583</span>, <span class="org-keyword">in</span> spawn_worker
    worker.init_process()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/workers/ggevent.py"</span>, line <span class="org-py-number">203</span>, <span class="org-keyword">in</span> init_process
    <span class="org-py-builtins">super</span>(GeventWorker, <span class="org-py-object-reference">self</span>).init_process()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/workers/base.py"</span>, line <span class="org-py-number">129</span>, <span class="org-keyword">in</span> init_process
    <span class="org-py-object-reference">self</span>.load_wsgi()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/workers/base.py"</span>, line <span class="org-py-number">138</span>, <span class="org-keyword">in</span> load_wsgi
    <span class="org-py-object-reference">self</span>.wsgi = <span class="org-py-object-reference">self</span>.app.wsgi()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/app/base.py"</span>, line <span class="org-py-number">67</span>, <span class="org-keyword">in</span> wsgi
    <span class="org-py-object-reference">self</span>.callable = <span class="org-py-object-reference">self</span>.load()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/app/wsgiapp.py"</span>, line <span class="org-py-number">52</span>, <span class="org-keyword">in</span> load
    <span class="org-keyword">return</span> <span class="org-py-object-reference">self</span>.load_wsgiapp()
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/app/wsgiapp.py"</span>, line <span class="org-py-number">41</span>, <span class="org-keyword">in</span> load_wsgiapp
    <span class="org-keyword">return</span> util.import_app(<span class="org-py-object-reference">self</span>.app_uri)
  File <span class="org-string">"/home/ec2-user/pulsar/venv/lib64/python3.6/dist-packages/gunicorn/util.py"</span>, line <span class="org-py-number">350</span>, <span class="org-keyword">in</span> import_app
    <span class="org-py-builtins">__import__</span>(module)
  File <span class="org-string">"/home/ec2-user/pulsar/push/webapp/app.py"</span>, line <span class="org-py-number">8</span>, <span class="org-keyword">in</span> &lt;module&gt;
    <span class="org-py-import-from">from</span> push.webapp <span class="org-py-import-from">import</span> ops_app
  .....
  File <span class="org-string">"/home/ec2-user/pulsar/core/ext/net_ext.py"</span>, line <span class="org-py-number">23</span>, <span class="org-keyword">in</span> HttpProxyList
    <span class="org-py-def-class">def</span> <span class="org-function-name">get</span>(<span class="org-py-object-reference">self</span>, region, <span class="org-py-variable-name">request_region</span>=config.APP_RUNNING_REGION, <span class="org-py-variable-name">stats</span>=<span class="org-py-pseudo-keyword">None</span>, <span class="org-py-variable-name">raw_docs</span>=<span class="org-py-pseudo-keyword">None</span>):
<span class="org-py-exception-name">AttributeError</span>: module <span class="org-string">'config'</span> has no attribute <span class="org-string">'APP_RUNNING_REGION'</span>
</pre>
</div>

<p>
从这个错误日志看出现了加载模块的错误 config 里面增加属性 APP_RUNNING_REGION. 但是当时我的操作只是更新代码，而没有进行重启。下面可以看到push_rpc_server一直在运行。
</p>

<pre class="example">
[ec2-user@host pulsar]$ supervisorctl
push_rpc_server                  RUNNING   pid 37526, uptime 28 days, 8:28:01
</pre>
</div>
</div>

<div id="outline-container-org8fa9d90" class="outline-2">
<h2 id="org8fa9d90"><span class="section-number-2">2</span> 事故分析</h2>
<div class="outline-text-2" id="text-2">
<p>
这个和gunicorn运行机制有关系：
</p>

<ol class="org-ol">
<li>gunicorn master首先会fork出多个workers</li>
<li>worker处理一定请求之后，gunicorn会reap掉某个worker</li>
<li>然后spwan worker保持worker数量</li>
</ol>

<p>
spawn worker是通过os.fork来实现的，worker里面得到的是app对象(app.wsgiapp.WSGIApplication)。这个app对象并没有load python code(gunicorn.util.import_app), 当在执行之前才会load(load_wsgiapp). 所以如果在worker里面load python code失败的话，那么就会一直出现这个错误。
</p>

<p>
如果代码保持不变的话，那么load python code应该是不会失败的。但是如果期间发生代码变化的话，那么可能就会出现错误。TODO(yan): 现在还没有找到可以简单复现的例子，但是从stacktrace来看，的确是因为访问模块不存在的属性导致的。
</p>

<p>
gunicorn上面有个选项是 `&#x2013;preload` 这个选项是在第一次启动的时候就把python code全部import上来，之后所有的worker都直接使用这个wsgi对象，不再会触发load python code逻辑。
</p>

<div class="org-src-container">
<pre class="src src-python"><span class="org-comment-delimiter"># </span><span class="org-comment">class Arbiter(object):</span>
<span class="org-py-def-class">def</span> <span class="org-function-name">setup</span>(<span class="org-py-object-reference">self</span>, app):
   ...
   <span class="org-keyword">if</span> <span class="org-py-object-reference">self</span>.cfg.preload_app:
       <span class="org-py-object-reference">self</span>.app.wsgi() <span class="org-comment"># &#36825;&#37324;&#20250;&#35302;&#21457;import&#36923;&#36753;</span>

<span class="org-comment-delimiter"># </span><span class="org-comment">class Worker(object)</span>
<span class="org-py-def-class">def</span> <span class="org-function-name">init_process</span>(<span class="org-py-object-reference">self</span>): <span class="org-comment"># worker&#37324;&#38754;&#21021;&#22987;&#21270;&#36923;&#36753;</span>
    ...
    <span class="org-py-object-reference">self</span>.load_wsgi()
    <span class="org-py-object-reference">self</span>.cfg.post_worker_init(<span class="org-py-object-reference">self</span>)

<span class="org-comment-delimiter"># </span><span class="org-comment">class BaseApplication(object):</span>
<span class="org-py-def-class">def</span> <span class="org-function-name">wsgi</span>(<span class="org-py-object-reference">self</span>):
    <span class="org-keyword">if</span> <span class="org-py-object-reference">self</span>.callable <span class="org-keyword">is</span> <span class="org-py-pseudo-keyword">None</span>:
        <span class="org-py-object-reference">self</span>.callable = <span class="org-py-object-reference">self</span>.load()
    <span class="org-keyword">return</span> <span class="org-py-object-reference">self</span>.callable
</pre>
</div>

<p>
使用这种方式可以保证在整个运行期间，整个worker使用的code不再会变化。
</p>
</div>
</div>
</div>
</body>
</html>
